- core/src/conversationProcessor.ts
- core/src/lmStream.ts
- core/src/memory.ts
- core/src/mentalModels.ts
- core/src/soul.ts
- core/tests/sentientModel.test.js
As discussed in discord, this PR allows the developer to add MentalModels to the chat. These are models that will get updated whenever new thoughts are generated and have the ability to inject themselves into the prompt.
The current model is a memory about a user. You could imagine models of environments, etc.
> add a way to add mental models to a soul

- core/package-lock.json
- core/package.json
- core/src/conversationProcessor.ts
- core/src/languageModels/index.ts
- core/src/lmProcessing.ts
- core/src/lmStream.ts
- core/src/memory.ts
- core/src/mentalModels.ts
- core/src/testing.ts
With this:
* upgrade OpenAI to 4.0.0 beta which has streaming support (and support for the new function types)
* Move some types out of using the standard OpenAI ones and into the social agi languageModel director.
This sets the stage for moving out openai to its own module by simplifying the use of openai down and making it easier to figure out what pieces we need to make sure work between different LanguageModels.
> an intermediate step to moving openai out to its own module

- core/src/cortexStep.ts
- core/src/languageModels/index.ts
- core/src/languageModels/openAI.ts
- core/src/programs/PeopleMemory/PersonModel.ts
- core/src/programs/participationStrategies/GroupParticipationStrategy.ts
- core/src/testing.ts
~this builds upon #61 so will become a smaller PR once that's merged.~
* add the ability to add function specification and model return of function calls to the executor output
* use that new return throughout the codebase, erroring now when no content returned.
This is an intermediate step to allowing experimentation with the function call system.
UPDATE: rebased #61
> add function call return support to the program executor

- tools/package.json
- tools/src/browser.ts
- tools/tests/browser.spec.ts
* fix build problem in the tool repo
* quick DX fixes to not have to install puppeteer separately in your repo, or know exactly how to configure it. The test file illustrates the usage change.
> quick DX fixes for using the web browser outside this repo

- core/src/next/languageModels/FunctionlessLLM.ts
- core/tests/next/CortexStep.spec.ts
- core/tests/next/languageModels/functionlessLLM.spec.ts
I've tested this on Mistral 7b, llama 13b, and nous heremes llama 13b and it works fairly well.
What this code does is take the function call and convert it to a user message with a requested JSON output. If there is an error, it recalls the LLM asking it to correct its error on the JSON.
This also supports a few of the services that do not support multiple system calls, but allowing a compression of all system calls into a single message at the top, followed by any assistant/user messages below that system message.
> better OSS model support for socialagi/next

- core/src/next/README.md
- core/src/next/languageModels/FunctionlessLLM.ts
- core/src/next/languageModels/index.ts
* handles the case where json is prefaced with something like "You should call the function with: "
* better retry logic, that won't repeat the same command messages over and over
* some documentation on how to use the new language processor
* fix the bug @kafischer pointed out of not adding new lines on system message concatenate
* fix package export
I also have now tried this with collective cognition mistral 7b.
> add better retry handling in the repo and documentation

- core/package-lock.json
- core/package.json
- tools/src/index.ts
- tools/src/sectionSplitter.ts
- tools/src/tokenCounter.ts
- tools/tests/browser.spec.ts
- tools/tests/sectionSplitter.spec.ts
On very large sites, the splitSections was going into infinite recursion when a section containing a single header was still too large to fit into a single tokenLength window.
This will now also export the isWithinTokenLimit for convenience and also has a couple of early return scenarios to speed up processing of way too high or way too low token counts.
> fix tooling but on really long pages

- core/.mocharc.json
- core/src/next/CortexStep.ts
- core/src/next/cognitiveFunctions.ts
- core/src/next/cortexScheduler.ts
- core/src/next/index.ts
- core/tests/next/CortexStep.spec.ts
- core/tests/next/cortexScheduler.spec.ts
- core/tests/shared/dotenv.ts
Bringing in and fixing things in the /next section that are necessary to switch over example code in the docs.
* bring back the CortexScheduler in /next (and test it)
* Add prompts from some of our demos for internal/externalDialog
* rename `stringCommand` (mark existing as deprecated) to `instruction` as "stringCommand" is too close to implementation rather than function
* support taking a function for `instruction` so that the instruction has access to the entity name / memory, etc
> features in /next for use in the docs

- docs/src/components/ApiKeyPopup.css
SImple fix to stop the API key popup from getting covered up by the scroll bars.
> simple z-index to get the popup over scroll bars

- core/package-lock.json
- core/package.json
- docs/package-lock.json
- docs/package.json
I'll self merge this, but bumps the latest version of core to v0.0.35 (already published to npm) and uses that in docs.
> bump versions

- docs/.gitignore
after you configure deployment for the docs, this gets added to the .gitignore so just checking this in. I will self merge this.
> ignore .vercel for deployment

- tools/package-lock.json
- tools/package.json
- tools/src/tokenCounter.ts
- tools/tests/browser.spec.ts
My speedup of the sectionSplitter had a bug on navigation of websites, etc. Ie, sections with heavy navigation and not content.
> fix tool sectionSplitter

- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
- docs/plugins/docusaurus-webpack/index.js
- docs/plugins/docusaurus-webpack/package.json
- memory/package-lock.json
- memory/package.json
Webpack can't handle the wasm or the models in there, so just ignore it since it's not used in the playground.
> version bump and ignore @xenova/transformers in doc section

- core/examples/metacognition.ts
- core/package-lock.json
- core/package.json
- core/src/next/cognitiveFunctions.ts
- core/tests/next/CortexStep.spec.ts
- core/tests/next/repetitiveDialog.spec.ts
- core/tests/next/repetitiveDialogHelpers/elonAndTheAstronaut.ts
- docs/docs/CortexStep/advancedExamples.md
- docs/package-lock.json
- docs/package.json
- docs/static/example-code/elonAI.js
- docs/static/example-code/persista.js
h/t @kafischer 
Asking a direct question like "How would X verbally respond?" ends up in the RLHFed assistant's mind instead of asking the LLM to model a different mind and complete a formatted response.
This PR switches over the cognitive functions and docs to better use this format.
notes:
I did *extensive* testing on this both in the automated tests and in the docs. Early on I saw some repetitive comments, but in adjusting the externalDialog and internalMonologue methods, I seem to have gotten rid of those. I also noticed that depending on the *character* played the LLM was throwing in random actions to speech. For instance, ElonAI never tried to do an action, but a stoner character would constantly add "*Tom takes another drag on his join*" kind of thing.
After adjusting the …
> update cognitiveFunctions to better use theory of mind simulation

- core/src/next/languageModels/FunctionlessLLM.ts
- core/tests/next/languageModels/functionlessLLM.spec.ts
This was the work I needed to do to make the Open Hermes 2.5 Mistral code work well. They only support a single system message, but rather than compress those all to the top, we instead change extra system messages to user messages. This seems to work really well for the various OSS models that I tested with single system message support.
> change how we handle oss models that only handle a single system message

- core/README.md
- core/src/cognitiveFunctions.ts
- core/src/cortexStep.ts
- core/src/languageModels/FunctionlessLLM.ts
- core/src/languageModels/index.ts
- core/src/languageModels/openAI.ts
- core/src/languageModels/reusableStream.ts
- core/tests/cognitiveFunctions.spec.ts
- core/tests/cortexStep.spec.ts
- core/tests/languageModels/openAi.spec.ts
- docs/docs/CortexStep/intro.md
note: this merges into the #128  PR branch (will reset when that is merged)
This PR moves streaming into the standardized API, and moves it away from "experimental"
Also moves the interface to have a settable "stream" on next...
```
step.next(externalDialog('say hello'), { stream: true })
```
> streaming support in a non-experimental way

- core/src/cortexStep.ts
- core/tests/cortexStep.spec.ts
- docs/docs/CortexStep/api.md
This allows you to to get a new CortexStep with completely updated memories. Useful for a few things, some are:
* reset memories after learning interlocutor name
* summarize early memories
* rewind to a previous state
> adds withUpdatedMemory function

- core/.eslintrc.cjs
- core/.eslintrc.json
- core/src/cognitiveFunctions.ts
- core/src/cortexStep.ts
- core/tests/cortexStep.spec.ts
This lets you strip a prefix and a suffix off a stream as it's coming in.
By necessity, you need to buffer some of the stream in order to do this, right now I keep two chunks buffered until the stream ends.
This lets you specify the prefix/suffix as either plain strings or regexes or functions that return regexes or strings (this lets you do things like use the entityName in the regexes).
The test in cortexstep checks to make sure the value matches the stream (it otherwise wouldn't without the prefix/suffix on externalDialog)
> stream manipulation

- core/src/cortexStep.ts
- core/src/languageModels/index.ts
- core/src/languageModels/openAI.ts
- core/tests/cortexStep.spec.ts
this PR lets you keep your language processor, but switch models out on a per .next or .compute call:
```typescript
const resp = await step.next(externalDialog("What does Bogus say?"), { model: "gpt-3.5-turbo-1106" })
```
> add the ability to switch the model on an individual next call

- core/src/cognitiveFunctions.ts
- core/tests/cognitiveFunctions.spec.ts
- core/tests/cortexStep.spec.ts
- core/tests/languageModels/functionlessLLM.spec.ts
mentalQuery is used to determine if an entity thinks a statement is true or false. It's very useful for flow control in a mental subroutine.
For instance:
`Samantha believes the user is lying`
or
`The user has answered the question correctly`
mentalQuery makes two calls to the underlying LanguageProcessor:
First, the entity thinks through their answer to the veracity of that statement and provides their reasoning.
Next, we extract the actual answer from their reasoning.
> mentalQuery cognitive function

- docs/docs/CortexStep/advancedExamples.md
- docs/docs/CortexStep/api.md
- docs/docs/intro.md
- docs/docs/languageModels.md
reflect some of the recent changes
- new LM executor class
- nextjs integration type stuff is no longer supported directly in socialagi
- reflext .next step options
- call out together & mistral
this isn't exactly reflected here but i think we've essentially downscoped socialagi to be about the minutia of modeling cognitive process flow
so like this on the main readme
```
SocialAGI aims to simplify the developer experience as much as possible in creating agentic and embodied chatbots called AI Souls, comprising thousands of linguistic instructions (managed by SocialAGI). Unlike traditional chatbots, these SocialAGI instructions will give digital souls personality, drive, ego, and will.
We are solving problems all the way across the AI souls stack, including:
How do I create the most …
```
> minor doc updates

- core/src/languageModels/Anthropic.ts
- core/tests/languageModels/anthropic.spec.ts
If you stop reading the stream before anthropic is ready then there is a triggered AbortController error that is uncatchable. This change lets Anthropic SDK control when this stream read ends.
> expected full read to fix anthropic bug

- legacy-docs/docs/intro.md
Did the simplest thing for now which is just to add an info call out right at the top of the homepage of the legacy docs.
> add a note on the legacy docs

- packages/engine/etc/engine.api.md
- packages/engine/src/mentalProcess.ts
builds off of #189 
these are the types to allow returning any of what's defined down there in the `MentalProcessReturnOptions`
Allowing you to switch to a new mental process and execute it now if you want.
> new process return type OPE-324

- packages/soul-engine-cli/src/communityInstaller.ts
special case the perception processors installation since that's always a single filename
> special case the perceptionProcessor

- package-lock.json
- packages/soul/package.json
- packages/soul/src/soul.ts
* If you call connect() twice on a soul it can do bad things, so protect that.
* it was missing the uuid dependency
* disconnect didn't do a *full* cleanup so connect() wouldn't work again
* for *now* just log a warn about all the listeners being removed... in the future I thing we should separate out disonnect() and destroy()
> bugs found while deploying reggie

- packages/soul-engine-cli/src/commands/index.ts
- packages/soul-engine-cli/src/commands/stores/index.ts
- packages/soul-engine-cli/src/commands/stores/pull.ts
- packages/soul-engine-cli/src/commands/stores/push.ts
- packages/soul-engine-cli/src/packageParser.ts
- packages/soul-engine-cli/src/rag/rag-file-poster.ts
- packages/soul-engine-cli/src/stores/hash.ts
- packages/soul-engine-cli/src/stores/pull.ts
- packages/soul-engine-cli/src/stores/push.ts
- packages/soul-engine-cli/src/stores/types.ts
dependent on https://github.com/opensouls/platform/pull/355
This adds commands to pull from and push to the engine's blueprint and organization stores.
As discussed in discord, this will create
`stores/:bucketName` or `stores/organization/:bucketName` in your working directory. Non-organization stores require a package.json with the blueprint name.
Commands work like:
```bash
npx soul-engine  stores pull docs
npx soul-engine stores push docs
```
or
```bash
npx soul-engine  stores pull organization/docs
npx soul-engine stores push organization/docs
```
When going through this pipeline, no chunking is done. Filenames represent the key, file content is exactly what will be embedded and stored.
This will allow for complex *local* pipelines to get your directory into shape, and then pushed up …
> tools to pull/push org and blueprint stores OPE-292

- packages/core/etc/core.api.md
- packages/core/src/WorkingMemory.ts
- packages/core/src/processors/messageRoleFixer.ts
- packages/core/tests/WorkingMemory.spec.ts
- packages/core/tests/processors/openAICompatibleProcessors.spec.ts
sorry for the mixed bag, noticed a bug and fixed it and figured I'd add these two things.
* adds workingMemory.at(idx) to return a memory at that index
* adds workingMemory.length which is an alias for workingMemory.memories.length
* fixes how we merge content in the processor, to restore working calls for models that enforce single system messages and alternating roles.
> add at, length, and fix merging content (fixing vision) OPE-357 OPE-358

- package-lock.json
- packages/core/package.json
- packages/engine/etc/engine.api.md
- packages/engine/package.json
- packages/engine/src/index.ts
- packages/soul-engine-cli/package.json
- packages/soul/package.json
dependent on https://github.com/opensouls/platform/pull/358
added model here for the future
The meat is that allowing people to specify options (filter, limit, distance) in the search of their stores. This changes the type which looks like a breaking change, but their filters weren't actually *working* (due to a bug in the engine) so I think it's ok to do this.
> updated types for vector

- packages/core/src/processors/AnthropicProcessor.ts
- packages/core/src/processors/OpenAIProcessor.ts
- packages/core/tests/processors/AnthropicProcessor.spec.ts
- packages/core/tests/processors/OpenAIProcessor.spec.ts
The bug we ran into was messages were combined using a new array content type which the encoder doesn't support yet. The tests didn't catch it because they only had a single user message in it and the bug only shows up when there are two user messages side by side (and no assistant between them).
This adds better tests for that, and also switches to using anthropics *actual* user info instead of an approximation from gpt4.
> fix token usage in anthropic to use the actual data from the API

- packages/engine/etc/engine.api.md
- packages/engine/src/index.ts
adds the type for previousMentalProcess and marks setNextProcess as deprecated.
> add previousMentalProcess to the useProcessManager hook

- packages/core/src/WorkingMemory.ts
- packages/core/src/processors/AnthropicProcessor.ts
- packages/core/src/processors/OpenAIProcessor.ts
in a streaming situation, it's possible the pending never gets resolved if there's an error in the request and/or an abort comes in.
> handle aborts more elegantly and fix hang in value promise

- package-lock.json
- packages/soul-engine-cli/package.json
- packages/soul-engine-cli/src/commands/logout.ts
- packages/soul-engine-cli/src/config.ts
- packages/soul-engine-cli/src/login.ts
- packages/soul/package.json
* add yjs dependency
* remove unused 'organization_id'
* add support for two different types of environment variable config setting:
** SOUL_ENGINE_CONFIG (which is the token pasted from /auth/cli)
** SOUL_ENGINE_API_KEY and SOUL_ENGINE_ORGANIZATION (which are what you would expect)
> add support for using environment variables instead of file system configs - OPE-395

- packages/soul/etc/soul.api.md
- packages/soul/src/index.ts
- packages/soul/src/soul.ts
2 things noticed by @neilsonnn and I during soul deployment:
* export SoulOpts so that we can use the type in other systems
* export getConnectedWebsocket so that we can multiplex souls over the connections.
> export soul opts OPE-387

- lerna.json
- package-lock.json
- packages/core/package.json
- packages/engine/package.json
- packages/pipeline/package.json
- packages/soul-engine-cli/package.json
- packages/soul-engine-cli/src/commands/dev.ts
- packages/soul/package.json
this is useful for apps that have side cars and we don't want the debug chat to open. Also fixes a bug with a race condition in the --once flag.
> fix once handling, add a --noopen flag to not launch the debug chat

- packages/engine/src/index.ts
- packages/soul-engine-cli/template/package.json
This removes the blueprint type from the public repos as there's no client side code that needs that anymore. Also adds a default "fast" model to the template making editing the default model easier.
> model config ope-503

- packages/soul/scripts/manualTest.ts
- packages/soul/src/soul.ts
node 22 introduced a new native WebSocket and it's experimental, and apparently broken.
This change will polyfill websocket with ws even if in node 22, but not bun or browser.
> make sure to polyfill for all versions of node OPE-494

- packages/core/src/processors/Processor.ts
- packages/core/src/sharedTypes/supportedModels.ts
> feat: Add Type Safety to Cognitive Steps and Processors [OPE-580]

- .github/npm-publish.yaml
these always need a little finageling but the idea is that you can run `npm run bump` which will create a release, and then this action should take over.
> publish to npm on release

- packages/soul/src/soul.ts
if token is not uuid, warn the user
> verify token format

- packages/core/.mocharc.json
- packages/core/src/WorkingMemory.ts
- packages/core/tests/WorkingMemory.spec.ts
* adding a new memory with `{..., region: 'xxx'}` now does what you'd expect and adds it to the bottom of the region.
* error on trying to use 'default' region name in `withRegion` (but is allowed in `withMemory`)
* add `withRegionalOrder` which sets a persistent regional order for future `withRegion` calls
* `withRegion` now adds new regions right before the default region (to say another way, right after the last defined region)
* reduce object creation by switching some .memories to .internalMemories
> regional ordering fixes OPE-614

- packages/core/etc/core.api.md
- packages/core/src/WorkingMemory.ts
clone.regionOrder throws an error under the production hardened environment because it's a readonly property on a hardened WorkingMemory.
This extends clone to take regionOrder as an override.
> add an override to clone to allow setting regionOrder in an ses environment

- packages/core/etc/core.api.md
- packages/core/src/WorkingMemory.ts
- packages/core/tests/WorkingMemory.spec.ts
* don't reserve word default, let people manipulate it
* add withOnlyRegions() to more easily get a section of the working memory.
> default handling imrovements

- packages/engine/etc/engine.api.md
- packages/engine/src/load.ts
- packages/soul/etc/soul.api.md
- packages/soul/src/soul.ts
* reexport SoulEvent (need that when parsing events in react)
* switch load into a non-async function.
> bugs from using integrator

- packages/engine/src/load.ts
Updated url to a dynamic import and added an extra `window === undefined` check
Caused by getting errors when building w/ Vite if url is imported
```
error during build:
node_modules/@opensouls/engine/dist/index.mjs (10:9): "fileURLToPath" is not exported by "__vite-browser-external", imported by "node_modules/@opensouls/engine/dist/index.mjs".
```
> Fix Node dependency
