plans/WEEK1.md

First pass at outlining the initial goals for the social agi project to be more useful and be able to be integrated into any application

Week 1 goals - great initial dev experience for samantha

---

core/README.md
core/examples/example2.ts
core/package-lock.json
core/package.json
core/src/TEMPLATES.ts
core/src/blueprint.ts
core/src/index.ts
core/src/lmStream.ts
core/src/soul.ts
core/src/utils.ts
core/tsconfig.json

- Add in ThoughtFrameworks - differentiating between Introspective framework and ReflectiveLP
- Rename a bunch of stuff for clarity

Add ThoughtFrameworks plus a bunch of cleanup

---

core/examples/example.ts
core/src/TEMPLATES.ts
core/src/action.ts
core/src/blueprint.ts
core/src/conversationProcessor.ts
core/src/lmStream.ts
core/src/soul.ts

This adds the ability to use "actions" in text (and this also includes #22 so can replace that PR).
So far I have only tried RAMBLE and it appears to be working really well.

add actions

---

core/src/TEMPLATES.ts
core/src/conversationProcessor.ts

- forward action input
- fix some issues with 3.5 getting confused about the actions
- add emobot discord

minor changes for action and action inputs to make them work with emojis on discord

---

core/examples/example.ts
core/src/conversationProcessor.ts
core/src/soul.ts

This allows the disabling of the break-up of the "message" thought which delays a bit the 2nd sentence and instead just ships the whole thing.

add a disableSayDelay option

---

core/src/conversationProcessor.ts

this adds an event when there's no more thoughts to process. This is useful when the soul is running as a web app and is doing request/response - this lets us know we can end the request.

add break event

---

.gitignore
README.md
core/src/lmProcessing.ts
core/src/lmProgram.ts
lmYield/.env-template
lmYield/.eslintrc.json
lmYield/.gitignore
lmYield/README.md
lmYield/examples/example.ts
lmYield/jest.config.js
lmYield/package-lock.json
lmYield/package.json
lmYield/src/index.ts
lmYield/src/utils.ts
lmYield/tsconfig.json

Will probably deprecate existing socialagi package and introduce scopes so this new one can be
`@socialagi/lmyield`

Add new LMYield package

---

core/examples/example.ts
core/src/TEMPLATES.ts
core/src/conversationProcessor.ts
core/src/index.ts
core/src/mentalModels.ts
core/src/programs/README.md
core/src/programs/index.ts
core/src/programs/participationStrategies/AlwyasReplyParticipationStrategy.ts
core/src/programs/participationStrategies/ConsumeOnlyParticipationStrategy.ts
core/src/programs/participationStrategies/GroupParticipationStrategy.ts
core/src/programs/participationStrategies/ParticipationStrategy.ts
core/src/programs/participationStrategies/index.ts
core/src/soul.ts
core/tests/participationStrategy.test.js
core/tests/sentientModel.test.js

* we have a better plan for "default context"
* refactor ParticipationStrategy into a class that can be added to conversations
* add better places for future "conversation" options

refactor participation strategy and drop "defaultContext"

---

core/src/languageModels/openAI.ts
core/src/programs/PeopleMemory/PeopleMemory.ts
core/src/programs/index.ts
core/src/soul.ts

These are just some changes I noticed while trying to *use* the main branch in a new project.

openAi typing fixes, naming change, exports

---

core/src/cortexStep.ts
core/src/languageModels/index.ts
core/src/languageModels/openAI.ts
core/tests/cortexStep.test.js

just a small refactor to use a switch statement instead of a nested if/else and to allow alternative language program executors to be used.

coretex refactor

---

core/package-lock.json
core/package.json
core/src/cortexScheduler.ts
core/src/index.ts
core/tests/cortexScheduler.test.js
core/tests/sentientModel.test.js

CortexScheduler: Scheduler registration and execution of MentalProcesses. The manager is essentially a converter between event driven and functional paradigms
A MentalProcess is:
- a container in which CortexSteps are taken. One version of CortexStep is returns and passed on the next one
- queued when received
- a queuing strategy for processes can be specified
- processes have an abort controller, which can be accessed in the queuing strategy
Goal is simplest possible api to convert from event driven arch to something that works with CortexStep
Trivial example:
```
const SamanthaReplies = async (
signal: AbortSignal,
newMemory: ChatMessage,
lastStep: CortexStep
) => {
let step = lastStep;
step = step.withMemory([newMemory]);
const shouts = await step.next(Action.EXTERNAL_DIALOG, { …
```

add cortex scheduler

---

core/src/cortexStep.ts
core/src/languageModels/openAI.ts

Found 1 bug and one annoyance in trying to force a coretex step to call a function, this PR fixes the bug (no functions being passed) and updates the API (having to add functionCall to the CALL_FUNCTION spec)

fix forced function calling

---

memory/package.json
tools/package.json

Fixes the memory and tools package.json to allow public publishing.

publishing changes to package.json

---

core/package-lock.json
core/package.json

this is the released version, so I will self-merge this one.

bump version

---

core/package-lock.json
core/package.json
core/src/next/CortexStep.ts
core/src/next/cognitiveFunctions.ts
core/tests/next/CortexStep.spec.ts
core/tests/next/repetitiveDialog.spec.ts
core/tests/next/repetitiveDialogHelpers/analyzer.ts
core/tests/next/repetitiveDialogHelpers/elon.ts
core/tests/next/repetitiveDialogHelpers/elonAndTheAstronaut.ts
core/tests/shared/dotenv.ts
docs/package-lock.json
docs/package.json
docs/static/example-code/elonAI.js

I changed the prompt a bit for the externalDialog and wrote a test that should show repetitiveness when it happens. Ran that over and over and didn't see anything. I also did manual testing and haven't seen it.
Also made some minor changes to the elon musk example too.
I also manually tested the other examples each a few times too.

improvements to repetitiveness

---

docs/docs/CortexStep/advancedExamples.md

fix bug in advanced example

---

docs/docs/CortexStep/examples.md

restore the tree of thoughts example, updating to use the latest /next code.

add back in the tree of thoughts example

---

core/examples/metacognition.ts

The real *bug* there was in the decision becoming decisionStep.

fix metacognition example

---

docs/static/example-code/samanthaEscalates.js
docs/static/example-code/samanthaShouts.js

- samantha shouts
- angering samantha

fix two examples

---

core/package-lock.json
core/package.json
core/src/next/cognitiveFunctions.ts
core/tests/cortexScheduler.spec.ts
core/tests/cortexStep.spec.ts
core/tests/functionTests.spec.ts
core/tests/next/CortexStep.spec.ts
core/tests/next/exampleAngelDevilConversation.ts
core/tests/next/examples.spec.ts
core/tests/next/repetitiveDialog.spec.ts
core/tests/next/repetitiveDialogHelpers/elonAndTheAstronaut.ts
core/tests/participationStrategy.spec.ts
core/tests/sentientModel.spec.ts
docs/package-lock.json
docs/package.json
docs/static/example-code/angelAndDevil.js
docs/static/example-code/elonAI.js
docs/static/example-code/persista.js
docs/static/example-code/samanthaEscalates.js

h/t @kafischer 
* There was a regression in decision making that's now fixed
* Internal Monologue will now follow instructions better
* Noticed edge cases in externalDialog adding extra characters
* Updated documentation examples to better align with new changes.
* Added additional testing based on failure cases from the existing examples.

example fixes and internal monologue fixes

---

core/src/next/cognitiveFunctions.ts
core/tests/next/cognitiveFunctions.spec.ts

Fix for https://github.com/opensouls/SocialAGI/issues/121

Fix LLM response boilerplate stripping bug

---

core/package-lock.json
core/package.json
core/src/next/cognitiveFunctions.ts
docs/package-lock.json
docs/package.json
docs/static/example-code/angelAndDevil.js
docs/static/example-code/samanthaConsidersSpeaking.js

* adjusts some settings around the two examples in the docs.

samantha talks less, angels and demons talk more.

---

core/tests/next/CortexStep.spec.ts
core/tests/next/evilCharacters.spec.ts

When exploring using the new preview models, we noticed a regression in character modeling and (what seemed like) alignment training. However, that issue appears gone (hopefully just a bug).
This is a test that will attempt to catch those issues in the future.

evilCharacters test

---

core/package-lock.json
core/package.json
docs/package-lock.json
docs/package.json

bumps the versions to v0.1.0 and uses that in docs.

version bump: v0.1.0

---

core/package-lock.json
core/package.json

version bump

---

memory/package-lock.json
memory/package.json

simple version bumps for dependencies in the memory project - especially transformers.js

dependency update for @opensouls/memory

---

core/scripts/jaeger.sh

very simply - make it easy to spin up jaeger in docker from the core directory.

a simple script to startup jaeger

---

core/src/cortexStep.ts
docs/docs/CortexStep/api2.md

`withMonologue(narrative: string)`
is useful for computing an internal thought using one sequence of steps, which is then added to a different step

Add a small bit of syntactic sugar

---

core/package-lock.json
core/package.json

bump to v0.1.5

---

tools/package-lock.json
tools/package.json
tools/tests/browser.spec.ts

@socialagi/tools upgrades

---

core/package-lock.json
core/package.json

bump to v0.1.6

---

package-lock.json
packages/soul-engine-cli/.gitignore
packages/soul-engine-cli/package.json
packages/soul-engine-cli/src/commands/init.ts
packages/soul-engine-cli/template/soul/README.md
packages/soul-engine-cli/template/soul/initialProcess.ts
packages/soul-engine-cli/template/soul/lib/cognitiveSteps.ts
packages/soul-engine-cli/template/soul/mentalProcesses/shouts.ts
packages/soul-engine-cli/template/soul/package.json
packages/soul-engine-cli/template/soul/subprocesses/_summarizes.ts
packages/soul-engine-cli/template/soul/subprocesses/learnsAboutTheUser.ts
packages/soul-engine-cli/template/soul/tsconfig.json
packages/soul-engine-cli/template/soul/{{entityName}}.md

this moves the template away from a different git clone and instead makes it part of the soul-engine CLI.

move template into the soul-engine itself

---

packages/core/src/WorkingMemory.ts
packages/core/tests/WorkingMemory.spec.ts

simple fix to make a nicer interface for replacing all the memories.

alias clone (nearly) with replace OPE-320

---

package-lock.json
packages/core/package.json
packages/engine/package.json
packages/soul-engine-cli/package.json
packages/soul-engine-cli/src/commands/install.ts
packages/soul/package.json

was still pointing at a branch

wrong community root

---

README.md
packages/core/README.md
packages/engine/README.md
packages/soul-engine-cli/README.md
packages/soul-engine-cli/src/commands/install.ts
packages/soul/README.md

updates or adds to all of the various READMEs in the repo.

update the readmes

---

packages/engine/etc/engine.api.md
packages/engine/src/index.ts

based on #177 - adds the PerceptionProcessor types.

perception processor types OPE-325

---

package-lock.json
packages/core/package.json
packages/engine/package.json
packages/soul-engine-cli/package.json
packages/soul/package.json

bump versions

---

lerna.json
package-lock.json
package.json
packages/core/package.json
packages/engine/package.json
packages/soul-engine-cli/package.json
packages/soul-engine-cli/template/package.json
packages/soul/package.json

this bumps all the dependencies to depend on each other correctly, and adds lerna to make sure they always do.

add lerna to fix deps stuff

---

packages/core/src/processors/OpenAIProcessor.ts

this should not have been exported

fix the export

---

package-lock.json
packages/core/package.json
packages/core/src/forkStream.ts
packages/core/src/processors/AnthropicProcessor.ts

oops - should not require node stream for this stuff. Instead, bring in a ponyfill for webstreams.

do not require node:stream

---

package-lock.json
packages/soul-engine-cli/package.json
packages/soul-engine-cli/src/commands/custom-models/createModel.ts
packages/soul-engine-cli/src/commands/custom-models/index.ts
packages/soul-engine-cli/src/commands/custom-models/list.ts
packages/soul-engine-cli/src/commands/dev.ts
packages/soul-engine-cli/src/commands/index.ts
packages/soul-engine-cli/src/commands/init.ts
packages/soul-engine-cli/src/customModels/customModel.ts

companion PR for https://github.com/opensouls/platform/pull/424
These don't *work* yet, but do let you list and create new custom models that get stored in the soul engine.

custom models ope-487

---

lerna.json
package-lock.json
packages/core/package.json
packages/engine/package.json
packages/pipeline/package.json
packages/soul-engine-cli/package.json
packages/soul-engine-cli/src/commands/apikey.ts
packages/soul/package.json

useful for setup scripts and solves a confusion some users had about finding their organization.

allow json output from apikey and also add organization output

---

packages/engine/etc/engine.api.md
packages/engine/src/index.ts

update the types necessary for https://github.com/opensouls/platform/pull/448

add the types for canceling and listing scheduled events

---

packages/soul-engine-cli/src/commands/dev.ts

"Soul Engine developers" unclear if that just anyone devleoping on the soul engine or someone developing with the soul engine

Clarify -l local message

---

packages/core/src/Memory.ts
packages/core/src/WorkingMemory.ts
packages/core/tests/WorkingMemory.spec.ts

see the tests for usage, but this adds very simple 'region' system which allows for easy swapping of one or more memories to a region, and a reordering based on region.

minimal memory region system.

---

packages/core/src/sharedTypes/eventLog.ts

deprecate the premonition field.

deprecated premonition - OPE-535

---

.github/workflows/npm-publish.yaml

change release type, move file to correct place

move workflow to correct directory

---

packages/engine/etc/engine.api.md
packages/engine/src/index.ts
packages/engine/src/load.ts

this just adds the types for memory integrator and the load function for the new soul.ts files

Feature/memory integrator types ope-613

---

packages/core/src/sharedTypes/supportedModels.ts

add the new  sonnet 3.5 and also add the gpt 3.5 model that isn't hooked to a date.

add new models
